import { describe, expect, it } from "vitest";
import engineMessages from "./__fixtures__/engine-messages.json";
import en from "@/messages/en.json";
import sv from "@/messages/sv.json";

/**
 * The solver's own sentences, and the Swedish this product shows for them.
 *
 * The engine refuses a week in sentences a school has to act on, and it has
 * no idea who is reading: it sends a stable code and the values, and the page
 * renders the language. Both halves live in different languages and different
 * deploys, so nothing but a test keeps them together.
 *
 * The fixture is the engine's catalogue, generated by
 * optimization-engine/tests/generate_engine_messages.py; the engine's own
 * suite fails when it goes stale. What fails HERE is a code the engine can
 * send that this build has no Swedish for. The page falls back to the English
 * in that case rather than showing nothing — see lib/engine-message.ts — so
 * this is a red test, not a broken screen, which is the right severity: it
 * ships, and it reads wrong.
 *
 * ARGUMENTS ARE CHECKED TOO, and that is the half that would otherwise rot
 * silently. next-intl throws when a message names an argument the caller did
 * not pass, and the fallback swallows it into English — so a Swedish sentence
 * that says {students} where the engine sends {classes} would look exactly
 * like an untranslated one, on the day a school's week was refused.
 */

type Messages = Record<string, unknown>;

/**
 * The ICU arguments a message takes, plural and select branches excluded.
 *
 * Depth is what does it: a branch is written in braces too, so a naive scan
 * reads `other {klasser}` as an argument called `other`. Only a brace opening
 * at the top level introduces one. The engine's own arguments_of scans its
 * side the same way, for the same reason.
 */
function argumentsOf(template: string): string[] {
  const names = new Set<string>();
  let depth = 0;

  for (let i = 0; i < template.length; i++) {
    const char = template[i];
    if (char === "}") {
      depth--;
      continue;
    }
    if (char !== "{") continue;
    depth++;
    if (depth !== 1) continue;
    const name = /^\w+/.exec(template.slice(i + 1))?.[0];
    if (name !== undefined) names.add(name);
  }

  return [...names].sort();
}

const codes = Object.keys(engineMessages as Messages).sort();
const swedish = (sv as Messages).engineMessages as Record<string, string>;
const english = (en as Messages).engineMessages as Record<string, string>;

describe("every sentence the engine can send", () => {
  it("has Swedish and English of its own", () => {
    expect(codes.length).toBeGreaterThan(0);
    expect(codes.filter((code) => !(code in swedish))).toEqual([]);
    expect(codes.filter((code) => !(code in english))).toEqual([]);
  });

  it("carries no Swedish for a code the engine cannot send", () => {
    // A code deleted engine-side leaves a translation nobody renders, which
    // the next reader has to guess about.
    expect(Object.keys(swedish).filter((code) => !codes.includes(code))).toEqual([]);
  });

  it.each(codes)("%s substitutes exactly the values the engine sends", (code) => {
    const fixture = (engineMessages as Record<string, string>)[code];
    expect(argumentsOf(swedish[code])).toEqual(argumentsOf(fixture));
    expect(argumentsOf(english[code])).toEqual(argumentsOf(fixture));
  });

  it("keeps the English identical to the engine's own", () => {
    // en.json is the fallback rendered when a code has no translation, and
    // the engine renders the same text for its logs. Two spellings of one
    // sentence is one of them being wrong.
    for (const code of codes) {
      expect(english[code]).toBe((engineMessages as Record<string, string>)[code]);
    }
  });
});
